blank_issues_enabled: false
contact_links:
  - name: 🧠 Consulta general
    url: https://github.com/AndresMaqueo/av-is-aviable/discussions
    about: Si tienes una idea o comentario general, publícalo en las discusiones.
